# Generated by Django 3.1.2 on 2021-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_db',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='user_db',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
